export const MONITOR_LIMITS = {
  MAX_LOCAL_MONITORS: 50,
  MAX_IMPORTED_MONITORS: 100,
  DEFAULT_CHECK_INTERVAL_SECONDS: 60,
  MIN_CHECK_INTERVAL_SECONDS: 30,
  MAX_CHECK_INTERVAL_SECONDS: 86400,
  DEFAULT_TIMEOUT_SECONDS: 10,
  MAX_TIMEOUT_SECONDS: 30,
  DEFAULT_RETENTION_DAYS: 30,
  MAX_CHECKS_HISTORY_PER_QUERY: 100,
  MAX_CONCURRENT_CHECKS: 3,
};
